### PR TITLE
fix: Dramatiq calls are no http requests

### LINKED ISSUE #2: Should not use `event.request` for non-HTTP requests
The `request` key is reserved for actual HTTP requests. I don't think it's a big deal to do what you're doing, but I wonder why this approach was taken?

### PR DESCRIPTION
**Pull request by untitaker**
Fix https://github.com/jmagnusson/sentry-dramatiq/issues/2

### CODE REVIEW

**Comment by jacobsvante** [comment]
Thanks @untitaker. Seems like the unit tests are failing though.

**Comment by untitaker** [comment]
@jmagnusson should work now?

**Comment by ramonsaraiva** [comment]
Can we please merge this and create a new release @jmagnusson?

**Comment by jacobsvante** [comment]
Merged and released as 0.3.0

**Pull request merged**
